### ISSUE TITLE
Found A Bug at Start Button

### ISSUE THREAD

**Issue by vasudevarao3** [iamwatchdogs/Stop_Watch_and_Countdown_Timer#3]
I have found a bug while looking at your project.

When I double click on start button, the stopwatch is not pausing and resetting.

Try disabling start button once the stopwatch is started or remove start once the stopwatch starts and display only pause button and when stopwatch is paused display only start button.

Hope this is helpful

**Comment by iamwatchdogs** [comment]
Thank you for finding the bug @vasudevarao3, I have verified what you have said and I find this as a potential bug that might lead to more issues in the future.

I'll be working on it the issue as soon as possible.

**Comment by iamwatchdogs** [comment]
I welcome anyone willing to work on this issue to fix the bug. If you are interested, comment here in the chat/issue-conversion.

**Comment by iamwatchdogs** [comment]
If you wish to work on this issue, I'll assign you. If nobody comes forth, I'll be fixing it by myself. Don't miss this opportunity, as this can be your first contribution to a real project.

**Comment by vasudevarao3** [comment]
I want to work on this issue please assign me

**Comment by iamwatchdogs** [comment]
Go ahead @vasudevarao3, just tag your PR when you're done.

**Comment by vasudevarao3** [comment]
I have fixed the bug, Please check PR #4

**Comment by iamwatchdogs** [comment]
Ok wait, Let me check...

**Comment by iamwatchdogs** [comment]
Sorry about the inconvenience, I have accidentally committed one of the suggestions in your pull request. Can you create a new PR so that I can review your code ?

**Comment by vasudevarao3** [comment]
I will Send it again.....

**Comment by vasudevarao3** [comment]
I have created new PR #5

**Comment by iamwatchdogs** [comment]
Thank you for your cooperation. I'll review it and notify you...
